// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/63b86d9398f19b3bebfe36ef
###
GET http://localhost:3000/contacts/622023f642f9ab4cd6e060b3
###
GET http://localhost:3000/contacts/622023f642f9ab4cd6e060b4


// PRODUCTION Deploy
###
GET https://cse-341-basic-example-w23.onrender.com/contacts
###
GET https://cse-341-basic-example-w23.onrender.com/contacts/63b86d9398f19b3bebfe36ef
###
GET https://cse-341-basic-example-w23.onrender.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://cse-341-basic-example-w23.onrender.com/contacts/622023f642f9ab4cd6e060b4